import Link from "next/link";
import { notFound } from "next/navigation";

import { SiteChrome } from "@/components/site-chrome";
import { getPreviewStory } from "@/lib/preview-content";

export default async function NewsStoryPage({ params }: { params: Promise<{ slug: string }> }) {
  const story = getPreviewStory((await params).slug);
  if (!story || story.mode !== "news") notFound();
  return <StoryPage story={story} />;
}

function StoryPage({ story }: { story: NonNullable<ReturnType<typeof getPreviewStory>> }) {
  return <SiteChrome active="home"><article className="story-page"><header className="story-header"><p className="micro-copy">{story.kicker}</p><h1>{story.title}</h1><p className="page-lede">{story.dek}</p><p className="story-updated">{story.updatedLabel} · <Link href="/en/about#editorial-fixtures">Why this label?</Link></p></header><section className="story-visual"><div className="visual-caption"><p className="micro-copy">Authored visual</p><h2>{story.visual.label}</h2><p>{story.visual.credit}</p></div><div className="story-orbit" aria-label="A four-part visual showing one central policy question connected to four standpoints"><b>One change</b>{story.perspectives.map((item) => <span key={item.label}>{item.label}</span>)}</div><p className="visual-limitation">Limit: {story.visual.limitation}</p></section><section className="story-summary"><div><p className="micro-copy">What changed</p><p>{story.whatChanged}</p></div><div><p className="micro-copy">Why it matters here</p><p>{story.whyItMatters}</p></div></section><section className="evidence-section"><div className="section-heading"><h2>Keep the kinds of knowledge apart.</h2><p>Each statement tells you what kind of support it has and how far it reaches.</p></div><div className="evidence-list">{story.evidence.map((item) => <article className={`evidence-card ${item.type}`} key={item.text}><p>{item.type}</p><h3>{item.text}</h3><small>{item.scope}</small><div>{item.sourceIds.map((sourceId) => <a href={`#${sourceId}`} key={sourceId}>Source {sourceId.replace("fixture-", "")}</a>)}</div></article>)}</div></section><section className="timeline-section"><p className="micro-copy">Timeline</p><ol>{story.timeline.map((item) => <li key={item.date}><strong>{item.date}</strong><span>{item.text}</span></li>)}</ol></section><section className="perspective-section"><p className="micro-copy">The same event, different starting points</p><h2>What each view can see—and may miss.</h2><div>{story.perspectives.map((item) => <article key={item.label}><h3>{item.label}</h3><dl><div><dt>Sees</dt><dd>{item.sees}</dd></div><div><dt>Values</dt><dd>{item.values}</dd></div><div><dt>Uses</dt><dd>{item.uses}</dd></div><div><dt>May miss</dt><dd>{item.mayMiss}</dd></div></dl></article>)}</div></section><section className="source-trail"><p className="micro-copy">Source trail</p><h2>What this page is built from.</h2>{story.sources.map((source) => <article id={source.id} key={source.id}><p>{source.publishedLabel}</p><h3><a href={source.url}>{source.title} <span aria-hidden="true">↗</span></a></h3><p>{source.publisher} · {source.use}</p></article>)}<p className="embed-gate">Social posts and media embeds are click-to-load and require an approved source, rights record, and caption. This teaching fixture has none to load.</p></section></article></SiteChrome>;
}
